/*
 * AUTO-GENERATED FILE — DO NOT EDIT.
 * Generated by scripts/generate-content-api.mjs
 * Types derived from config.yml
 */

// Widget -> TS mapping is conservative (select = string, etc.)

export type Slug = string;

export type Post = {
	slug: Slug;
	draft: boolean;
	title: string;
	featuredImage?: string;
	tags?: string[];
	body: string;
	excerpt: string;
};

export type Tag = {
	slug: Slug;
	title: string;
	description?: string;
	categoryImage?: string;
	body: string;
	excerpt: string;
};

export type Person = {
	slug: Slug;
	name: string;
	bio?: string;
	photo?: string;
	body: string;
	excerpt: string;
};

export type Podcast = {
	slug: Slug;
	title: string;
	date?: string;
	description?: string;
	audio?: string;
	duration?: string;
	length?: string;
	body: string;
	excerpt: string;
};

export type SettingsSite = {
	name: string; // "site"
	siteTitle?: string;
	siteDescription?: string;
	defaultImage?: string;
	accentColour?: string;
	body: string;
};

