/*
 * AUTO-GENERATED FILE — DO NOT EDIT.
 * Generated by scripts/generate-content-api.mjs
 * Types derived from config.yml
 */

// Widget -> TS mapping is conservative (select = string, etc.)

export type Slug = string;

export type Post = {
	slug: Slug;
	draft: boolean;
	title: string;
	featuredImage?: string;
	tags?: string[];
	body: string;
	excerpt: string;
};

export type Tag = {
	slug: Slug;
	title: string;
	description?: string;
	categoryImage?: string;
	body: string;
	excerpt: string;
};

export type Person = {
	slug: Slug;
	name: string;
	role?: string;
	bio?: string;
	photo?: string;
	body: string;
	excerpt: string;
};

export type Podcast = {
	slug: Slug;
	title: string;
	draft?: boolean;
	description?: string;
	date?: string;
	thumb?: string;
	mp3?: string;
	duration?: string;
	length?: string;
	talent?: string[];
	tags?: string[];
	body: string;
	excerpt: string;
};

export type Font = {
	slug: Slug;
	title: string;
	stack?: string;
	weightHeading?: number;
	fontFaceNotes?: string;
	body: string;
	excerpt: string;
};

export type Typography = {
	slug: Slug;
	title: string;
	fontSize?: number;
	scale?: number;
	lineHeight?: number;
	measure?: number;
	notes?: string;
	body: string;
	excerpt: string;
};

export type ColorScheme = {
	slug: Slug;
	title: string;
	prime: unknown;
	accent: unknown;
	second: unknown;
	gray: unknown;
	text: unknown;
	light: unknown;
	body: string;
	excerpt: string;
};

export type SettingsSite = {
	name: string; // "site"
	siteTitle?: string;
	siteDescription?: string;
	defaultImage?: string;
	activeColorScheme?: string;
	activeHeadingsFont?: string;
	activeBodyFont?: string;
	activeTypography?: string;
	body: string;
};

