/*
 * AUTO-GENERATED FILE — DO NOT EDIT.
 * Generated by scripts/generate-content-api.mjs
 * Content API derived from config.yml
 */
import { readAll, readOne, readDoc } from '$lib/server/content/read';
import type { ReadResult } from '$lib/server/content/read';
import type {
	Post,
	Tag,
	Person,
	Podcast,
	SettingsSite,
} from '$lib/content/types.generated';

function asString(x: unknown): string {
	return typeof x === 'string' ? x : '';
}
function asBoolean(x: unknown): boolean {
	return x === true;
}
function asNumber(x: unknown): number {
	return typeof x === 'number' && Number.isFinite(x) ? x : 0;
}
function asStringArray(x: unknown): string[] {
	if (Array.isArray(x)) return x.filter((v): v is string => typeof v === 'string');
	if (typeof x === 'string' && x.length) return [x];
	return [];
}
function pick<T>(x: T): T {
	return x;
}

function mapPost(row: ReadResult): Post {
	const data = (row.data ?? {}) as Record<string, unknown>;
	const body = typeof row.body === 'string' ? row.body : '';
	return {
		slug: row.meta?.slug ?? '',
		draft: asBoolean(data['draft']),
		title: asString(data['title']),
		featuredImage: asString(data['featuredImage']),
		tags: asStringArray(data['tags']),
		body,
		excerpt: body ? body.slice(0, 200) : ''
	};
}

export async function getPosts(opts: { includeDrafts?: boolean } = {}): Promise<Post[]> {
	const { includeDrafts = false } = opts;
	const rows = await readAll('posts');
	let items = rows.map(mapPost);
	if (!includeDrafts) items = items.filter((p) => (p as any).draft !== true);
	return items;
}

export async function getPost(slug: string, opts: { includeDrafts?: boolean } = {}): Promise<Post | null> {
	const row = await readOne('posts', slug);
	if (!row) return null;
	const item = mapPost(row);
	if (opts.includeDrafts !== true) {
		if ((item as any).draft === true) return null;
	}
	return item;
}

export function joinPostsWithTags(posts: Post[], tags: Tag[]): Post[] {
	const index = new Map(tags.map((t) => [t.slug, t] as const));
	return posts.map((p) => {
		const resolved = Array.isArray((p as any)['tags'])
			? ((p as any)['tags'] as unknown[])
				.filter((s): s is string => typeof s === 'string')
				.map((s) => index.get(s))
				.filter(Boolean)
			: [];
		return { ...(p as any), tagsObjects: resolved } as Post;
	});
}

function mapTag(row: ReadResult): Tag {
	const data = (row.data ?? {}) as Record<string, unknown>;
	const body = typeof row.body === 'string' ? row.body : '';
	return {
		slug: row.meta?.slug ?? '',
		title: asString(data['title']),
		description: asString(data['description']),
		categoryImage: asString(data['categoryImage']),
		body,
		excerpt: body ? body.slice(0, 200) : ''
	};
}

export async function getTags(): Promise<Tag[]> {
	const rows = await readAll('tags');
	return rows.map(mapTag);
}

export async function getTag(slug: string): Promise<Tag | null> {
	const row = await readOne('tags', slug);
	return row ? mapTag(row) : null;
}

function mapPerson(row: ReadResult): Person {
	const data = (row.data ?? {}) as Record<string, unknown>;
	const body = typeof row.body === 'string' ? row.body : '';
	return {
		slug: row.meta?.slug ?? '',
		name: asString(data['name']),
		bio: asString(data['bio']),
		photo: asString(data['photo']),
		body,
		excerpt: body ? body.slice(0, 200) : ''
	};
}

export async function getPeople(): Promise<Person[]> {
	const rows = await readAll('people');
	return rows.map(mapPerson);
}

export async function getPerson(slug: string): Promise<Person | null> {
	const row = await readOne('people', slug);
	return row ? mapPerson(row) : null;
}

function mapPodcast(row: ReadResult): Podcast {
	const data = (row.data ?? {}) as Record<string, unknown>;
	const body = typeof row.body === 'string' ? row.body : '';
	return {
		slug: row.meta?.slug ?? '',
		title: asString(data['title']),
		date: asString(data['date']),
		description: asString(data['description']),
		audio: asString(data['audio']),
		duration: asString(data['duration']),
		length: asString(data['length']),
		body,
		excerpt: body ? body.slice(0, 200) : ''
	};
}

export async function getPodcasts(): Promise<Podcast[]> {
	const rows = await readAll('podcasts');
	return rows.map(mapPodcast);
}

export async function getPodcast(slug: string): Promise<Podcast | null> {
	const row = await readOne('podcasts', slug);
	return row ? mapPodcast(row) : null;
}

function mapSettingsSite(row: ReadResult): SettingsSite {
	const data = (row.data ?? {}) as Record<string, unknown>;
	const body = typeof row.body === 'string' ? row.body : '';
	return {
		name: 'site',
		siteTitle: asString(data['siteTitle']),
		siteDescription: asString(data['siteDescription']),
		defaultImage: asString(data['defaultImage']),
		accentColour: asString(data['accentColour']),
		body
	};
}

export async function getSettingsSite(): Promise<SettingsSite> {
	const row = await readDoc('settings', 'site');
	return mapSettingsSite(row);
}

